### ISSUE TITLE
update INSTALL.md

### ISSUE THREAD

**Issue by dpaiton** [delvtech/pypechain#15]
The install.md looks like it was copied from elf-simulations and not rewritten to be for pypechain.

Also, when I clone the repo and run `pip install pypechain[all]` I get an error 
```
zsh: no matches found: pypechain/pypechain[all]
```
I don't think the pyproject is set up correct.

**Comment by sentilesdal** [comment]
@dpaiton I don't get this error at all.  The proper command is in the INSTALL.md so maybe it was updated.  The command is:
```bash
pip install ".[all]"
```

Closing for now, we can reopen if the problem arises again.
