### ISSUE TITLE
Improve call() method overloading

### ISSUE THREAD

**Issue by sentilesdal** [delvtech/pypechain#51]
see #50 for original issue.

In web3.py function construction and execution are separated:

```python
doSomething = deployed_contract.functions.doSomething(x)
result = doSomething.call()
```

This leads to problems if we want to provide typed return values from call() when doSomething() is overloaded:

```python
doSomething_x = deployed_contract.functions.doSomething(x)
doSomething_xy = deployed_contract.functions.doSomething(x,y)

result_x: int = doSomething_x.call()
result_xy: (int, int) = doSomething_x.call()
```

For example, if x and xy versions have the same return signature, then we don't want to declare multiple call() methods. If they do, then we want multple methods, but how do we know which one to call? We can't. We either have to provide multiple return signatures or have doSomething(x) and doSomething(x,y) return different call() methods.

A future improvement would be to change the invocation pattern to:

```python
call_options = CallOptions(block_number=1234)
result = deployed_contract.functions.doSomething(...args, call_options=call_options)
```

For now, if there are multiple return signatures we simply set the return signature to Any and avoid overloading call() all together. 

We should either do the future improvement OR list all return signatures in call() and let the user figure out which overlaoded signature they are calling.

**Comment by slundqui** [comment]
`call` reports the correct type hints based on input arguments
